### ISSUE TITLE
page empty on my local.

### ISSUE THREAD

**Issue by zhouzl7** [flowforfrank/d3-treemap#2]
Are there instructions for implementation? Why is the page empty when I open index.html on my local
![捕获](https://user-images.githubusercontent.com/33414045/100494807-4188ee80-3180-11eb-9d9d-17ea37bac467.PNG)

**Comment by flowforfrank** [comment]
A detailed tutorial is available on [webtips.dev](https://www.webtips.dev/how-to-make-stunning-data-visualizations-with-d3-js) where you can follow the instructions for the implementation. You need to fire up a webserver in order to use the app. I suggest using [http-server](https://www.npmjs.com/package/http-server) for that purpose.
